### ISSUE TITLE
base_controller not running correctly in simulation

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#641]
as reported by @ipa-bfb
they seem to be drifting...needs investigation....

**Comment by floweisshardt** [comment]
~~are you sure this is the base_controller? What I observed was just the simulated robot model slightly drifting in gazebo (independent of wheel positions and controller)~~

**Comment by bbrito** [comment]
try to use cob_teleop and see if it works...

**Comment by floweisshardt** [comment]
sorry, ignore my comment. Seems as the recently introduced commits broke driving the robot in gazebo. we'll have to investigate.

**Comment by fmessmer** [comment]
Why are the `steer_target_velocity` that high? Is this rad/sec? @ipa-mdl 
```
rostopic echo /base/twist_controller/wheel_commands 
header: 
  seq: 52189
  stamp: 
    secs: 52
    nsecs: 923000000
  frame_id: ''
drive_target_velocity: [0.0, 0.0, 0.0]
steer_target_velocity: [7.60710124957176, -10.0, -10.0]
steer_target_position: [0.0, -3.141592653589793, 0.0]
steer_target_error: [1.395496564844115, -2.722543136645081, -3.048259837630063]
```

~~Is the non-zero value in the `steer_target_position` some kind of "homing position"? Where is this defined?~~
It's [this line for cob4](https://github.com/ipa320/cob_robots/blob/264c1eb53bf04462af0b61ecc2e42afc13c3752f/cob_hardware_config/common/cob4_base_controller.yaml#L31) and [this line for raw3](https://github.com/ipa320/cob_robots/blob/264c1eb53bf04462af0b61ecc2e42afc13c3752f/cob_hardware_config/common/raw3_base_controller.yaml#L32)

In gazebo all joints are spawned at zero position...thus there is a big initial `steer_target_error`...thus the `steer_target_velocity` are high....
We either need to:
 - add this to the `cob_gazebo_ros_control` plugin
 - or we try to spawn the wheels in gazebo at the correct starting position (there is an [argument](https://github.com/ipa320/cob_simulation/blob/indigo_dev/cob_bringup_sim/launch/robot.launch#L11) that can be used for specifying joint positions...but this was always buggy) https://github.com/ros-simulation/gazebo_ros_pkgs/issues/93
 - or we find an option for not using this parameter when using simulation...
