### ISSUE TITLE
use laser_filter pipeline for scanner

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#732]
according to @ipa-jba, [laser_filters](http://wiki.ros.org/laser_filters) is quite powerful

investigate setting up a proper filter_pipeline for e.g. the sick scanners that would replace:
 - [cob_scan_filter](https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/laser_scan_filter.launch) via http://wiki.ros.org/laser_filters#LaserScanAngularBoundsFilter
 - ~[max_range_fix](https://github.com/ipa320/cob_driver/pull/358) via http://wiki.ros.org/laser_filters#LaserScanRangeFilter~

@ipa-bnm @ipa-fmw FYI

**Comment by fmessmer** [comment]
@ipa-srd
can you explain again, why it was necessary to avoid `NaN` in the laser scan and replace it with `max_range`?

**Comment by stefandoerr** [comment]
With https://github.com/ipa320/cob_driver/pull/358 max range measurements are properly set, i.e. their values are >= than the configured max_range of the respective laser scanner. This is needed so that a node can properly identify max range measurements within the ranges array. For example. the localization module normally filters out max range measurements to avoid matching those measurements against the map. 
However, in the current setup, this would lead to an undesired behavior in the costmap which will discard those max range measurements for ray tracing. In open areas where you have a lot of max range measurements, this leads to the problem that dynamic objects are not cleared properly. With the feature implemented by @ipa-jba in https://github.com/ros-perception/laser_filters/pull/56, this problem can be resolved. The filter sets all max range measurements to inf. Together with setting the `inf_is_valid` param in the obstacle_layer to true, this fixes the problem.

**Comment by stefandoerr** [comment]
Example config:
```
scan_filter_chain:
 - name: self_meas
   type: LaserScanAngularBoundsFilter
   params:
     lower_angle: 0.78
     upper_angle: 3.91
 - name: max_range
   type: LaserScanRangeFilter
   params:
     use_message_range_limits: true
upper_replacement_value: .inf

```
Example node

```
+  <node pkg="laser_filters" type="scan_to_scan_filter_chain" name="laser_filter">
+    <rosparam command="load" file="$(find striml_hardware_config)/robots/$(arg robot)/config/laser_filter_chain.yaml" />
+    <remap from="scan" to="/base_laser_front/scan" />
+    <remap from="scan_filtered" to="scan" />
+  </node>
```

**Comment by jabbenseth** [comment]
in the example config `upper_replacement_value` should be on the same indentation level as `use_message_range`

**Comment by fmessmer** [comment]
once we use this filter_chain, i.e. setting out-of-range values to `inf`, where (in which nav.yaml) is the `inf_is_valid` param to be set?

**Comment by fmessmer** [comment]
the `LaserScanAngularBoundsFilter` has weird behavior:
 - it **cuts away** scan points in the given interval rather than keeping just those
 - also negative values for the angle parameters seem not to cause problems

thus, I'm just adding the `LaserScanRangeFilter` and keeping the current `cob_scan_filter` for the angular bounds

**Comment by stefandoerr** [comment]
http://wiki.ros.org/costmap_2d/hydro/obstacles
and add in pkg_nav_config/robots/<robot>/nav/move_base_local_costmap_params.yaml in the respective obstacle layer

**Comment by fmessmer** [comment]
I tested the related PRs today, i.e. "max_range" of sick_s300 + RangeFilter pipeline + inf_is_valid in costmap

However, the behavior is not as expected, i.e. ranges that are set to `inf` in the laser scan used as a costmap observation source, does not really clear the costmap properly...
@ipa-srd has confirmed that the behavior seen is not correct

@ipa-jba can we have a look at this together sometime next week?

**Comment by fmessmer** [comment]
to debug raytracing, @ipa-srd suggested to temporarily remove the inflation layer to better see the actually blocked cells

**Comment by stefandoerr** [comment]
without having looked into code the chain: setting max range to inf -> using inf_is_valid in costmap does not help, i.e. occupied areas are not cleared although the ray tracing of max range measurements should go through the cell. A successfully tested workaround is to have a `LaserScanRangeFilter`setting max range to some value higher than costmap bounds but lower than obstacle_range param in costmap params and using this scan msg exclusively for move_base.

Example of the node:

```
  <node pkg="laser_filters" type="scan_to_scan_filter_chain" name="laser_filter_planning">
    <rosparam command="load" file="$(find striml_hardware_config)/robots/$(arg robot)/config/laser_filter_chain_planning.yaml" />
    <remap from="scan" to="scan" />
    <remap from="scan_filtered" to="scan_planning" />
  </node>
```
and the laser filter config:
```

scan_filter_chain:
 - name: max_range_to_finite
   type: LaserScanRangeFilter
   params:
     use_message_range_limits: false
     upper_threshold: 16.0
     upper_replacement_value: 16.0
```

move_base_local_costmap_params.yaml:

```
# The parameters for the rolling_window (must be set if rolling_window = true)
width: 8.0         # default: 10
height: 8.0        # default: 10
resolution: 0.05   # default: 0.05
origin_x: 0.0       # default: 0.0
origin_y: 0.0       # default: 0.0

obstacle_layer:

  # Definition of the sensors/observation sources
  observation_sources: laser_scan_front

  # Parameters of the source: laser_scan_front
  laser_scan_front:
    sensor_frame: base_laser_link # The frame of the origin of the sensor, default: ""
    topic: /scan_planning       # The topic on which sensor data comes in for this source, default: source_name
    data_type: LaserScan                # The data type associated with the topic, default: "PointCloud"
    marking: true                       # Whether or not this observation is used to mark obstacles, default: true
    clearing: true                      # Whether or not this observation is used to clear out freespace, default: false


  # The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters
  obstacle_range: 18.0  # default: 2.5

  # The default range in meters at which to raytrace out obstacles from the map using sensor data
  raytrace_range: 18.0  # default: 3.0
```


@ipa-fxm fyi
